### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by jinan-zhou** [lizhihao6/Forward-Warp#3]
Thank you for the amazing repo! This fucntion is absolutely a missing part from PyTorch.

However, I encountered  the following error during install:
```
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/ai/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/username/anaconda3/envs/ai/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

Does anyone have any ideas how to deal with it?

**Comment by lizhihao6** [comment]
Thanks for your attention.
Please edit the /home/username/anaconda3/envs/ai/lib/python3.7/dist-packages/torch/utils/cpp_extension.py
change ['ninja','-v'] into ['ninja','--v']

This is a bug that has nothing to do with the code, if there are still questions you can reply this.

**Comment by lizhihao6** [comment]
I'm afraid this is a problem caused by the update of the header file caused by the pytorch version update, which I also encountered in pytorch 1.7, and I haven't found a good solution for now.

**Comment by hurjunhwa** [comment]
Have you tried using different cudatoolkit version when installing pytorch?
I got the same error with CUDA11.1 + Pytorch 1.8.1, but changing to CUDA 10.1 + Pytorch 1.8.1 solved the problem.

**Comment by lizhihao6** [comment]
Yeah, it seems like incompatibility of the CUDA version.
