### ISSUE TITLE
About total_step-1

### ISSUE THREAD

**Issue by tkkcc** [lizhihao6/Forward-Warp#7]
Hi, I'm confused about this -1. It looks like a mistake to me. Can you explain the purpose?
https://github.com/lizhihao6/Forward-Warp/blob/27fe46cd766d960e10d07b3a3156816a8e63ed8e/Forward_Warp/cuda/forward_warp_cuda_kernel.cu#L35

**Comment by lizhihao6** [comment]
It seems like a bug. Have you tried with total_step instead of total_step-1?

**Comment by tkkcc** [comment]
Yes, I use total_step. It seems ok.

**Comment by lizhihao6** [comment]
Thx, I have fixed that.
