### ISSUE TITLE
Questions about the usage of this project

### ISSUE THREAD

**Issue by hitachinsk** [lizhihao6/Forward-Warp#9]
Hi, I'm a new comer to the optical flow field, and I am attracted by this excellent project. As for as I know, the `grid_sample` function in `pytorch` solves the problem about backward flow warping. For example, if I have frame1 and frame2, I can use the flow1->2 to warp the information from frame2 to frame1. What about your codes? Does flow forward warping mean I can adopt the flow1->2 to warp the information from frame1 to frame2? I'm looking forward to your reply, thank you.

**Comment by lizhihao6** [comment]
First of all, if you use grid sample (backward warp) you sample the output from the input, specifically I know the input image and where each point of the output will be mapped to in the input, so you can sample the output from the input. But this sampled position is a float point number, and quantization to pixels is not precise. The forward warp is the opposite, it also knows the input image, but it also knows where each point in the input will be mapped to in the output, and samples the output from the mapped image (of course, the mapped points are also float point numbers, and quantization will be imprecise, so we generally use forward and backward together). Simply put, backward is to first sample and then map, forward is to first map and then sample.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Kaidong Zhang ***@***.***>
发送时间: Monday, June 28, 2021 7:06:33 PM
收件人: lizhihao6/Forward-Warp ***@***.***>
抄送: Subscribed ***@***.***>
主题: [lizhihao6/Forward-Warp] Questions about the usage of this project (#9)


Hi, I'm a new comer to the optical flow field, and I am attracted by this excellent project. As for as I know, the grid_sample function in pytorch solves the problem about backward flow warping. For example, if I have frame1 and frame2, I can use the flow1->2 to warp the information from frame2 to frame1. What about your codes? Does flow forward warping mean I can adopt the flow1->2 to warp the information from frame1 to frame2? I'm looking forward to your reply, thank you.

―

**Comment by hitachinsk** [comment]
@lizhihao6 Thanks for your answer! So, your codes solve the latter condition, which uses the flow1->2 to warp frame1 to frame2?

**Comment by lizhihao6** [comment]
Yeap

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Kaidong Zhang ***@***.***>
发送时间: Monday, June 28, 2021 9:59:16 PM
收件人: lizhihao6/Forward-Warp ***@***.***>
抄送: lizhihao6 ***@***.***>; Mention ***@***.***>
主题: Re: [lizhihao6/Forward-Warp] Questions about the usage of this project (#9)


@lizhihao6<https://github.com/lizhihao6> Thanks for your answer! So, your codes solve the latter condition, which uses the flow1->2 to warp frame1 to frame2?

―

**Comment by hitachinsk** [comment]
Thanks for your help, god bless you!
